import { ListView } from "std-widgets.slint";
import { Table, TableAdapter } from "table.slint";
import { TableHeader } from "table-header.slint";
import { TableRow, TableRowView } from "table-row.slint";
import { Theme } from "theme.slint";

export { TableRow }

// table
export { TableAdapter }

export component MainWindow inherits Window {
    in property <[TableRow]> rows;

    background: Theme.palette.black;
    min-height: Theme.window.min-height;
    min-width: Theme.window.min-width;
    title: "Romman";

    VerticalLayout {
        height: parent.height - Theme.window.padding;
        // table
        // padding-top: 170px;
        vertical-stretch: 1;
        width: parent.width - Theme.window.padding;

        HorizontalLayout {
            TableHeader {
                text: "File";
                width: 45%;
            }

            TableHeader {
                text: "Platform";
                width: 35%;
            }

            TableHeader {
                text: "Status";
                width: 20%;
            }
        }

        ListView {
            for data[idx] in rows: TableRowView {
                even: mod(idx, 2) == 0;
                filename: data.filename;
                platform: data.platform;
                status: data.status;
            }
        }
    }

    // Table {
    //     width: parent.width - Theme.window.padding;
    //     height: parent.height - Theme.window.padding;
    // }
}
