import { Theme } from "theme.slint";
import { Table, TableAdapter } from "table.slint";

export { TableAdapter }

export component MainWindow inherits Window {
    title: "Romman";
    min-width: Theme.window.min-width;
    min-height: Theme.window.min-height;
    background: Theme.palette.black;

    Table {
        width: parent.width - Theme.window.padding;
        height: parent.height - Theme.window.padding;
    }
}
