import { ListView, ProgressIndicator } from "std-widgets.slint";
import { TableHeader } from "table-header.slint";
import { TableRow, TableRowBackend, TableRowView } from "table-row.slint";
import { Theme } from "theme.slint";

export { TableRow, TableRowBackend }

export component MainWindow inherits Window {
    in property <[TableRow]> rows;
    in property <float> percent;

    background: Theme.palette.black;
    min-height: Theme.window.min-height;
    min-width: Theme.window.min-width;
    preferred-height: 720px;
    preferred-width: 1280px;
    title: @tr("Rom Boy");
    icon: @image-url("../assets/logo.png");

    VerticalLayout {
        height: parent.height - Theme.window.padding;
        vertical-stretch: 1;
        width: parent.width - Theme.window.padding;

        HorizontalLayout {
            TableHeader {
                text: "File";
                width: 55%;
            }

            TableHeader {
                text: "Platform";
                width: 15%;
            }

            TableHeader {
                text: "Status";
                width: 20%;
            }

            TableHeader {
                width: 10%;

                ProgressIndicator {
                    width: parent.width / 2;
                    height: parent.height / 2;
                    progress: percent;
                }
            }
        }

        ListView {
            for data[idx] in rows: TableRowView {
                even: mod(idx, 2) == 0;
                filename: data.filename;
                in_library: data.in_library;
                platform: data.platform;
                status: data.status;
            }
        }
    }
}
