import { ListView, Button } from "std-widgets.slint";
import { Theme } from "theme.slint";

export struct TableRow {
    filename: string,
    in_library: bool,
    platform: image,
    status: string,
}

export global TableRowBackend {
    pure callback clicked(string, bool);
}

export component TableRowView inherits Window {
    in property <bool> even;
    in property <bool> in_library;
    in property <image> platform;
    in property <string> filename;
    in property <string> status;
    in property <float> percent;

    VerticalLayout {
        ta := TouchArea {

            row := Rectangle {
                background: even ? Theme.table.even-background : Theme.table.odd-background;
                height: 35px;

                GridLayout {
                    padding-left: Theme.table.text-padding;

                    Text {
                        color: even ? Theme.table.even-text : Theme.table.odd-text;
                        font-family: Theme.table.font;
                        font-size: Theme.table.font-size;
                        height: Theme.table_header.height - 5px;
                        overflow: elide;
                        text: root.filename;
                        vertical-alignment: center;
                        width: 55%;
                    }

                    Image {
                        horizontal-alignment: left;
                        source: root.platform;
                        width: 15%;
                    }

                    Text {
                        color: root.in_library ? #5E8F68 : grey;
                        font-family: Theme.table.font;
                        font-size: Theme.table.font-size;
                        height: Theme.table_header.height - 5px;
                        text: root.status;
                        vertical-alignment: center;
                        width: 20%;
                    }

                    Rectangle {
                        height: Theme.table_header.height;

                        TouchArea {
                            height: 100%;
                            width: 100%;

                            clicked => {
                                TableRowBackend.clicked(root.filename, root.in_library);
                            }

                            Rectangle {
                                background: root.in_library ? black : #304F41;
                                border-color: root.in_library ? grey : #5E8F68;
                                border-radius: 2px;
                                border-width: 1px;
                                height: 24px;
                                width: 62px;

                                Text {
                                    font-size: Theme.table.font-size - 2pt;
                                    padding-left: 5px;
                                    text: root.in_library ? "remove" : "add";
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    states [
        active-hover when ta.has-hover: {
            row.background: Theme.table.odd-background;
        }
    ]
}
