import { ListView, Button } from "std-widgets.slint";
import { Theme } from "theme.slint";

export struct TableRow {
    filename: string,
    platform: image,
    status: string,
}

export global TableRowBackend {
    pure callback clicked(string);
}

export component TableRowView inherits Window {
    in property <bool> even;
    in property <image> platform;
    in property <string> filename;
    in property <string> status;

    VerticalLayout {
        ta := TouchArea {

            row := Rectangle {
                background: even ? Theme.table.even-background : Theme.table.odd-background;
                height: 35px;

                GridLayout {
                    padding-left: Theme.table.text-padding;

                    Text {
                        color: even ? Theme.table.even-text : Theme.table.odd-text;
                        font-family: Theme.table.font;
                        font-size: Theme.table.font-size;
                        height: Theme.table_header.height - 5px;
                        overflow: elide;
                        text: root.filename;
                        vertical-alignment: center;
                        width: 55%;
                    }

                    Image {
                        horizontal-alignment: left;
                        source: root.platform;
                        width: 15%;
                    }

                    Text {
                        color: root.status == "In Library" ? #5E8F68 : #CF6D24;
                        font-family: Theme.table.font;
                        font-size: Theme.table.font-size;
                        height: Theme.table_header.height - 5px;
                        text: root.status;
                        vertical-alignment: center;
                        width: 20%;
                    }

                    Rectangle {
                        height: Theme.table_header.height;

                        TouchArea {
                            height: 100%;
                            width: 100%;

                            clicked => {
                                TableRowBackend.clicked("test test");
                            }

                            Rectangle {
                                border-color: root.status == "In Library" ? #5E8F68 : grey;
                                border-radius: 2px;
                                border-width: 1px;
                                background: root.status == "In Library" ? #304F41 : black;
                                height: 22px;
                                width: 52px;

                                Text {
                                    font-size: Theme.table.font-size - 2pt;
                                    padding-left: 5px;
                                    text: root.status == "In Library" ? "add" : "remove";
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    states [
        active-hover when ta.has-hover: {
            row.background: Theme.table.odd-background;
        }
    ]
}
