export struct Durations {
    fast: duration,
    medium: duration,
    slow: duration,
}

export struct Palette {
    // solids
    black: brush,
    white: brush,

    // gradients
    main-gradient: brush,
}

export struct Window {
    min-height: length,
    min-width: length,
    padding: length,
}

export struct Table {
    even-background: color,
    even-text: color,
    font-size: length,
    font: string,
    odd-background: color,
    odd-text: color,
    platform-image-size: length,
    text-height: length,
    text-padding: length,
}

export struct TableHeader {
    background: color,
    border-background-active: color,
    border-background: color,
    border: length,
    cell-background-active: color,
    color: color,
    height: length,
}

export global Theme {
    in property <Durations> durations: {
        fast: 125ms,
        medium: 200ms,
        slow: 500ms,
    };

    in property <Palette> palette: {
        // solids
        black: #000000,
        white: #ffffff,

        // gradients
        main-gradient: @linear-gradient(180deg, #000000 0%, #000000 100%),
    };

    in property <Window> window: {
        min-height: 240px,
        min-width: 575px,
        padding: 20px,
    };

    in property <Table> table: {
        even-background: #000000,
        even-text: #c1c1c1,
        font-size: 12pt,
        font: "Tahoma",
        odd-background: #0f0f0f,
        odd-text: #ffffff,
        platform-image-size: 14px,
        text-height: 14px,
        text-padding: 12px,
    };

    in property <TableHeader> table_header: {
        background: #1c1c1c,
        border-background-active: #1f1f1f,
        border-background: #2e2e2e,
        border: 2px,
        cell-background-active: #131313,
        color: #cfcfcf,
        height: 40px,
    };
}
